name: Spread Tests

on:
    pull_request:
    workflow_dispatch:
    push: { branches: [main] }

jobs:
    tests-build:
        name: Build Snaps
        uses: ./.github/workflows/build.yaml

    tests-spread:
        name: Test Runner
        needs: [tests-build]
        runs-on: ${{ matrix.arch.runs-on }}

        strategy:
            matrix:
                arch:
                    - { name: amd64, runs-on: ubuntu-latest }
                    - { name: arm64, runs-on: ubuntu-24.04-arm }

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v7
            - name: Install LXD
              uses: canonical/setup-lxd@v1
            - name: Install Snapcraft
              run: sudo snap install --classic snapcraft
            - name: Download Artifact
              uses: actions/download-artifact@v7
              with:
                  path: .
                  name: gleam-snap-${{ matrix.arch.name }}
            - name: Run Spread Tests
              run: snapcraft test lxd
